name: common_locale_data
description: A type-safe and tree-shakable API to access translated common data (measurement units, date fields, country names etc...)
version: 2.1.0
homepage: https://github.com/xvrh/common_locale_data

environment:
  sdk: '^3.5.0'

dependencies:
  collection: ^1.17.2
  intl: '>=0.18.0 <1.0.0'

dev_dependencies:
  analyzer:
  build_runner:
  dart_style: ^2.3.7
  http:
  json_annotation:
  json_serializable:
  lints:
  path:
  pool:
  process_runner:
  test:
  yaml: